### Gauss Elimination

Gaussian elimination can be divided into three steps: 
1) Pivoting
2) Forward elimination
3) Backward substitution

The last step - backward substitution - is very reminiscent of the equation for finding $x$ that we saw in the previous exercise, after we had already found $y$, and while using the matrix $U$: these two methods are conceptually similar. Today we will focus on the first two steps in the calculation.

Let us begin with the first step - pivoting:

In [1]:
import numpy as np

def perform_partial_pivoting(A, b, k):
    """
    Performs Partial Pivoting for column k in matrix A and vector b. 
    """

    relative_pivot_row = np.argmax(np.abs(A[k:, k]))
    pivot_row = k + relative_pivot_row
    
    if pivot_row != k:
        # This method is called "fancy indexing" - I strongly recommend to know it and use it!
        A[[k, pivot_row]] = A[[pivot_row, k]]
        b[[k, pivot_row]] = b[[pivot_row, k]]
    return A, b
    

A_matrix = np.array([
    [2, 5, 2],
    [1, 2, 4],
    [4, 2, 3]
], dtype=float)

b_vector = np.array([1, 7, 8], dtype=float)

# Printing before pivoting
print("Matrix A before pivoting column 0:")
print(A_matrix)

# Calling the function for the first column (k=0) 
A_pivoted, b_pivoted = perform_partial_pivoting(A_matrix, b_vector, 0)

# Final prints outside the function

print(f"Matrix A:\n{A_pivoted}")
print(f"Vector b:\n{b_pivoted}")


Matrix A before pivoting column 0:
[[2. 5. 2.]
 [1. 2. 4.]
 [4. 2. 3.]]
Matrix A:
[[4. 2. 3.]
 [1. 2. 4.]
 [2. 5. 2.]]
Vector b:
[8. 7. 1.]


Note: you need to preform this method for all the matrix's cloumns.

In [2]:
def forward_elimination(A_orig, b_orig):
    """
    Performs the Forward Elimination stage of Gaussian elimination.
    """
    A = A_orig.astype(float).copy()
    b = b_orig.astype(float).copy()
    n = len(b)

    for k in range(n - 1):
        # Step 1: Partial Pivoting
        A, b = perform_partial_pivoting(A, b, k)

        # Step 2: Elimination
        for i in range(k + 1, n):
            factor = A[i, k] / A[k, k]
            A[i, k:] -= factor * A[k, k:] 
            b[i] -= factor * b[k] 

    return A, b

A_matrix = np.array([
    [2, 5, 2],
    [1, 2, 4],
    [4, 2, 3]
], dtype=float)

b_vector = np.array([1, 7, 8], dtype=float)

# Calling the function
A_triangular, b_updated = forward_elimination(A_matrix, b_vector)

# Final prints outside the function

print(f"Upper Triangular Matrix A:\n{A_triangular}")
print(f"Updated Vector b:\n{b_updated}")

Upper Triangular Matrix A:
[[4.     2.     3.    ]
 [0.     4.     0.5   ]
 [0.     0.     3.0625]]
Updated Vector b:
[ 8.    -3.     6.125]
